# Use Nginx image
FROM nginx:alpine

# Copy the custom HTML file to the default Nginx public directory
COPY public/index.html /usr/share/nginx/html/

# Expose port 80 to the outside world - documentation purposes 
EXPOSE 80